name: ds_env
channels:
    - conda-forge
    - defaults
dependencies:
    - pip
    - python
    - numpy
    - openblas
    - swig
    - pip:
        - pypesto
        - petab
        - pandas
        - amici